export { default as productsRoute } from "./products.route";
export { default as workshopsRoute } from "./workshops.route";
export { default as membersRoute } from "./members.route";
export { default as servicesRoute } from "./services.route";
export { default as contactsRoute } from "./contacts.route";
export { default as utilsRoute } from "./utils.route";
export { default as diyRoute } from "./diy.route";
export { default as shortCoursesRoute } from "./short_courses.route";
export { default as searchRoute } from "./search.route";
